services:
  - type: web
    name: shiftease-demo
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PIN
        value: "1234"
